### ISSUE TITLE
Feature Request - Add the PUMP command

### ISSUE THREAD

**Issue by PaulGWebster** [bbriggs/bitbot#136]
<daemon> #pump abuse.txt
bitbot(internal dialog ... god damn this guy)
bitbot, let me look in https://github.com/ircart/ircart/blob/master/big/abuse.txt
bitbot: yeah its here ....
<bitbot> PUMPIN ... cat https://github.com/ircart/ircart/blob/master/big/abuse.txt
<bitbot>   
<bitbot>    ALL ABOARD THE ABUSE CABOOSE!
<bitbot>          *CHUGGA-GHUGGA-CHOO-CHOO!*
<bitbot>     (o (o (o (o  (o (o(o)
<bitbot>     ____==== _____     (o)
<bitbot>    [ ABUSE  ] ]_o|_n_n__][.
<bitbot> -+-[________]_|__|________)<+--+--+--+--+
<bitbot> \\\\oo\\\\oo\\'oo\OOOO-|\oo\\_\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> -+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> -+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> _\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> <+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> \_\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> .
<bitbot> )<--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> \\_\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> )
<bitbot> [.
<bitbot> _)<-+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> o\\_\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> )
<bitbot> o)
<bitbot> ][.
<bitbot> __)<+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> \oo\\_\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> o)
<bitbot> (o)
<bitbot> _][.
<bitbot> ___)<--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> |\oo\\_\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> (o)
<bitbot>  (o)
<bitbot> __][.
<bitbot> ____)<-+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> -|\oo\\_\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> o(o)
<bitbot>   (o)
<bitbot> n__][.
<bitbot> _____)<+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> O-|\oo\\_\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> (o(o)
<bitbot>    (o)
<bitbot> _n__][.
<bitbot> ______)<--+--+--+--+--+--+--+--+--+--+--+
<bitbot> OO-|\oo\\_\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>  (o(o)
<bitbot>     (o)
<bitbot> n_n__][.
<bitbot> _______)<-+--+--+--+--+--+--+--+--+--+--+
<bitbot> OOO-|\oo\\_\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> o (o(o)
<bitbot>      (o)
<bitbot> _n_n__][.
<bitbot> ________)<+--+--+--+--+--+--+--+--+--+--+
<bitbot> OOOO-|\oo\\_\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> (o (o(o)
<bitbot> _     (o)
<bitbot> |_n_n__][.
<bitbot> |________)<--+--+--+--+--+--+--+--+--+--+
<bitbot> \OOOO-|\oo\\_\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>  (o (o(o)
<bitbot> __     (o)
<bitbot> o|_n_n__][.
<bitbot> _|________)<-+--+--+--+--+--+--+--+--+--+
<bitbot> o\OOOO-|\oo\\_\\\\\\\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>   (o (o(o)
<bitbot> ___     (o)
<bitbot> _o|_n_n__][.
<bitbot> __|________)<+--+--+--+--+--+--+--+--+--+
<bitbot> oo\OOOO-|\oo\\_\\\\\\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> o  (o (o(o)
<bitbot> ____     (o)
<bitbot> ]_o|_n_n__][.
<bitbot> |__|________)<--+--+--+--+--+--+--+--+--+
<bitbot> 'oo\OOOO-|\oo\\_\\\\\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> (o  (o (o(o)
<bitbot> _____     (o)
<bitbot>  ]_o|_n_n__][.
<bitbot> _|__|________)<-+--+--+--+--+--+--+--+--+
<bitbot> \'oo\OOOO-|\oo\\_\\\\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>  (o  (o (o(o)
<bitbot>  _____     (o)
<bitbot> ] ]_o|_n_n__][.
<bitbot> ]_|__|________)<+--+--+--+--+--+--+--+--+
<bitbot> \\'oo\OOOO-|\oo\\_\\\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> o (o  (o (o(o)
<bitbot> = _____     (o)
<bitbot>  ] ]_o|_n_n__][.
<bitbot> _]_|__|________)<--+--+--+--+--+--+--+--+
<bitbot> o\\'oo\OOOO-|\oo\\_\\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> (o (o  (o (o(o)
<bitbot> == _____     (o)
<bitbot>   ] ]_o|_n_n__][.
<bitbot> __]_|__|________)<-+--+--+--+--+--+--+--+
<bitbot> oo\\'oo\OOOO-|\oo\\_\\\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>  (o (o  (o (o(o)
<bitbot> === _____     (o)
<bitbot> E  ] ]_o|_n_n__][.
<bitbot> ___]_|__|________)<+--+--+--+--+--+--+--+
<bitbot> \oo\\\\oo\\'oo\OOOO-|\oo\\_\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> o (o (o  (o (o(o)
<bitbot> ==== _____     (o)
<bitbot> SE  ] ]_o|_n_n__][.
<bitbot> ____]_|__|________)<--+--+--+--+--+--+--+
<bitbot> \\oo\\'oo\OOOO-|\oo\\_\\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> (o (o (o  (o (o(o)
<bitbot> _==== _____     (o)
<bitbot> USE  ] ]_o|_n_n__][.
<bitbot> _____]_|__|________)<-+--+--+--+--+--+--+
<bitbot> \\\oo\\'oo\OOOO-|\oo\\_\\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>  (o (o (o  (o (o(o)
<bitbot> __==== _____     (o)
<bitbot> BUSE  ] ]_o|_n_n__][.
<bitbot> ______]_|__|________)<+--+--+--+--+--+--+
<bitbot> \\\\oo\\'oo\OOOO-|\oo\\_\\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> o (o (o (o  (o (o(o)
<bitbot> ___==== _____     (o)
<bitbot> ABUSE  ] ]_o|_n_n__][.
<bitbot> _______]_|__|________)<--+--+--+--+--+--+
<bitbot> o\\\\oo\\'oo\OOOO-|\oo\\_\\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot> (o (o (o (o  (o (o(o)
<bitbot> ____==== _____     (o)
<bitbot>  ABUSE  ] ]_o|_n_n__][.
<bitbot> ________]_|__|________)<-+--+--+--+--+--+
<bitbot> oo\\\\oo\\'oo\OOOO-|\oo\\_\\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>  (o (o (o (o  (o (o(o)
<bitbot>  ____==== _____     (o)
<bitbot> [ ABUSE  ] ]_o|_n_n__][.
<bitbot> [________]_|__|________)<+--+--+--+--+--+
<bitbot> \oo\\\\oo\\'oo\OOOO-|\oo\\_\\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>   (o (o (o (o  (o (o(o)
<bitbot>   ____==== _____     (o)
<bitbot>  [ ABUSE  ] ]_o|_n_n__][.
<bitbot> -[________]_|__|________)<--+--+--+--+--+
<bitbot> \\oo\\\\oo\\'oo\OOOO-|\oo\\_\\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>    (o (o (o (o  (o (o(o)
<bitbot>    ____==== _____     (o)
<bitbot>   [ ABUSE  ] ]_o|_n_n__][.
<bitbot> -+[________]_|__|________)<-+--+--+--+--+
<bitbot> \\\oo\\\\oo\\'oo\OOOO-|\oo\\_\\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>     (o (o (o (o  (o (o(o)
<bitbot>     ____==== _____     (o)
<bitbot>    [ ABUSE  ] ]_o|_n_n__][.
<bitbot> -+-[________]_|__|________)<+--+--+--+--+
<bitbot> \\\\oo\\\\oo\\'oo\OOOO-|\oo\\_\\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>      (o (o (o (o  (o (o(o)
<bitbot>      ____==== _____     (o)
<bitbot>     [ ABUSE  ] ]_o|_n_n__][.
<bitbot> -+--[________]_|__|________)<--+--+--+--+
<bitbot> \\\\\oo\\\\oo\\'oo\OOOO-|\oo\\_\\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>       (o (o (o (o  (o (o(o)
<bitbot>       ____==== _____     (o)
<bitbot>      [ ABUSE  ] ]_o|_n_n__][.
<bitbot> -+--+[________]_|__|________)<-+--+--+--+
<bitbot> \\\\\\oo\\\\oo\\'oo\OOOO-|\oo\\_\\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>        (o (o (o (o  (o (o(o)
<bitbot>        ____==== _____     (o)
<bitbot>       [ ABUSE  ] ]_o|_n_n__][.
<bitbot> -+--+-[________]_|__|________)<+--+--+--+
<bitbot> \\\\\\\oo\\\\oo\\'oo\OOOO-|\oo\\_\\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>         (o (o (o (o  (o (o(o)
<bitbot>         ____==== _____     (o)
<bitbot>        [ ABUSE  ] ]_o|_n_n__][.
<bitbot> -+--+--[________]_|__|________)<--+--+--+
<bitbot> \\\\\\\\oo\\\\oo\\'oo\OOOO-|\oo\\_\\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>          (o (o (o (o  (o (o(o)
<bitbot>          ____==== _____     (o)
<bitbot>         [ ABUSE  ] ]_o|_n_n__][.
<bitbot> -+--+--+[________]_|__|________)<-+--+--+
<bitbot> \\\\\\\\\oo\\\\oo\\'oo\OOOO-|\oo\\_\\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>           (o (o (o (o  (o (o(o)
<bitbot>           ____==== _____     (o)
<bitbot>          [ ABUSE  ] ]_o|_n_n__][.
<bitbot> -+--+--+-[________]_|__|________)<+--+--+
<bitbot> \\\\\\\\\\oo\\\\oo\\'oo\OOOO-|\oo\\_\\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>            (o (o (o (o  (o (o(o)
<bitbot>            ____==== _____     (o)
<bitbot>           [ ABUSE  ] ]_o|_n_n__][.
<bitbot> -+--+--+--[________]_|__|________)<--+--+
<bitbot> \\\\\\\\\\\oo\\\\oo\\'oo\OOOO-|\oo\\_\\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>             (o (o (o (o  (o (o(o)
<bitbot>             ____==== _____     (o)
<bitbot>            [ ABUSE  ] ]_o|_n_n__][.
<bitbot> -+--+--+--+[________]_|__|________)<-+--+
<bitbot> \\\\\\\\\\\\oo\\\\oo\\'oo\OOOO-|\oo\\_\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>              (o (o (o (o  (o (o(o)
<bitbot>              ____==== _____     (o)
<bitbot>             [ ABUSE  ] ]_o|_n_n__][.
<bitbot> -+--+--+--+-[________]_|__|________)<+--+
<bitbot> \\\\\\\\\\\\\oo\\\\oo\\'oo\OOOO-|\oo\\_\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>               (o (o (o (o  (o (o(o)
<bitbot>               ____==== _____     (o)
<bitbot>              [ ABUSE  ] ]_o|_n_n__][.
<bitbot> -+--+--+--+--[________]_|__|________)<--+
<bitbot> \\\\\\\\\\\\\\oo\\\\oo\\'oo\OOOO-|\oo\\_\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                (o (o (o (o  (o (o(o)
<bitbot>                ____==== _____     (o)
<bitbot>               [ ABUSE  ] ]_o|_n_n__][.
<bitbot> -+--+--+--+--+[________]_|__|________)<-+
<bitbot> \\\\\\\\\\\\\\\oo\\\\oo\\'oo\OOOO-|\oo\\_\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                 (o (o (o (o  (o (o(o)
<bitbot>                 ____==== _____     (o)
<bitbot>                [ ABUSE  ] ]_o|_n_n__][.
<bitbot> -+--+--+--+--+-[________]_|__|________)<+
<bitbot> \\\\\\\\\\\\\\\\oo\\\\oo\\'oo\OOOO-|\oo\\_
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                   (o (o (o (o  (o (o(o)
<bitbot>                   ____==== _____     (o)
<bitbot>                  [ ABUSE  ] ]_o|_n_n__][.
<bitbot> -+--+--+--+--+--+[________]_|__|________)<
<bitbot> \\\\\\\\\\\\\\\\\\oo\\\\oo\\'oo\OOOO-|\oo\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                    (o (o (o (o  (o (o(o)
<bitbot>                    ____==== _____     (o)
<bitbot>                   [ ABUSE  ] ]_o|_n_n__][.
<bitbot> -+--+--+--+--+--+-[________]_|__|________)<
<bitbot> \\\\\\\\\\\\\\\\\\\oo\\\\oo\\'oo\OOOO-|\oo\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                     (o (o (o (o  (o (o(o)
<bitbot>                     ____==== _____     (o)
<bitbot>                    [ ABUSE  ] ]_o|_n_n__][.
<bitbot> -+--+--+--+--+--+--[________]_|__|________)
<bitbot> \\\\\\\\\\\\\\\\\\\\oo\\\\oo\\'oo\OOOO-|\oo
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                      (o (o (o (o  (o (o(o)
<bitbot>                      ____==== _____     (o)
<bitbot>                     [ ABUSE  ] ]_o|_n_n__][
<bitbot> -+--+--+--+--+--+--+[________]_|__|________
<bitbot> \\\\\\\\\\\\\\\\\\\\\oo\\\\oo\\'oo\OOOO-|\o
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                       (o (o (o (o  (o (o(o)
<bitbot>                       ____==== _____     (o
<bitbot>                      [ ABUSE  ] ]_o|_n_n__]
<bitbot> -+--+--+--+--+--+--+-[________]_|__|_______
<bitbot> \\\\\\\\\\\\\\\\\\\\\\oo\\\\oo\\'oo\OOOO-|\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                        (o (o (o (o  (o (o(o
<bitbot>                        ____==== _____     (
<bitbot>                       [ ABUSE  ] ]_o|_n_n__
<bitbot> -+--+--+--+--+--+--+--[________]_|__|______
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\oo\\\\oo\\'oo\OOOO-|
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                         (o (o (o (o  (o (o(
<bitbot>                         ____==== _____
<bitbot>                        [ ABUSE  ] ]_o|_n_n_
<bitbot> -+--+--+--+--+--+--+--+[________]_|__|_____
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\oo\\\\oo\\'oo\OOOO-
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                          (o (o (o (o  (o (o
<bitbot>                          ____==== _____
<bitbot>                         [ ABUSE  ] ]_o|_n_n
<bitbot> -+--+--+--+--+--+--+--+-[________]_|__|____
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\\oo\\\\oo\\'oo\OOOO
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                           (o (o (o (o  (o (
<bitbot>                           ____==== _____
<bitbot>                          [ ABUSE  ] ]_o|_n_
<bitbot> -+--+--+--+--+--+--+--+--[________]_|__|___
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\\\oo\\\\oo\\'oo\OOO
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                            (o (o (o (o  (o
<bitbot>                            ____==== _____
<bitbot>                           [ ABUSE  ] ]_o|_n
<bitbot> -+--+--+--+--+--+--+--+--+[________]_|__|__
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\\\\oo\\\\oo\\'oo\OO
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                             (o (o (o (o  (o
<bitbot>                             ____==== _____
<bitbot>                            [ ABUSE  ] ]_o|_
<bitbot> -+--+--+--+--+--+--+--+--+-[________]_|__|_
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\\\\\oo\\\\oo\\'oo\O
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                              (o (o (o (o  (
<bitbot>                              ____==== _____
<bitbot>                             [ ABUSE  ] ]_o|
<bitbot> -+--+--+--+--+--+--+--+--+--[________]_|__|
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\\\\\\oo\\\\oo\\'oo\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                               (o (o (o (o
<bitbot>                               ____==== ____
<bitbot>                              [ ABUSE  ] ]_o
<bitbot> -+--+--+--+--+--+--+--+--+--+[________]_|__
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\oo\\\\oo\\'oo
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                                (o (o (o (o
<bitbot>                                ____==== ___
<bitbot>                               [ ABUSE  ] ]_
<bitbot> -+--+--+--+--+--+--+--+--+--+-[________]_|_
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\oo\\\\oo\\'o
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                                 (o (o (o (o
<bitbot>                                 ____==== __
<bitbot>                                [ ABUSE  ] ]
<bitbot> -+--+--+--+--+--+--+--+--+--+--[________]_|
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\oo\\\\oo\\'
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                                  (o (o (o (
<bitbot>                                  ____==== _
<bitbot>                                 [ ABUSE  ]
<bitbot> -+--+--+--+--+--+--+--+--+--+--+[________]_
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\oo\\\\oo\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                                   (o (o (o
<bitbot>                                   ____====
<bitbot>                                  [ ABUSE  ]
<bitbot> -+--+--+--+--+--+--+--+--+--+--+-[________]
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\oo\\\\oo\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                                    (o (o (o
<bitbot>                                    ____====
<bitbot>                                   [ ABUSE
<bitbot> -+--+--+--+--+--+--+--+--+--+--+--[________
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\oo\\\\oo
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                                     (o (o (
<bitbot>                                     ____===
<bitbot>                                    [ ABUSE
<bitbot> -+--+--+--+--+--+--+--+--+--+--+--+[_______
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\oo\\\\o
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                                      (o (o
<bitbot>                                      ____==
<bitbot>                                     [ ABUSE
<bitbot> -+--+--+--+--+--+--+--+--+--+--+--+-[______
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\oo\\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                                       (o (o
<bitbot>                                       ____=
<bitbot>                                      [ ABUS
<bitbot> -+--+--+--+--+--+--+--+--+--+--+--+--[_____
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\oo\\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                                        (o (
<bitbot>                                        ____
<bitbot>                                       [ ABU
<bitbot> -+--+--+--+--+--+--+--+--+--+--+--+--+[____
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\oo\\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                                         (o 
<bitbot>                                         ___
<bitbot>                                        [ AB
<bitbot> -+--+--+--+--+--+--+--+--+--+--+--+--+-[___
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\oo\
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                                          (o
<bitbot>                                          __
<bitbot>                                         [ A
<bitbot> -+--+--+--+--+--+--+--+--+--+--+--+--+--[__
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\oo
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+
<bitbot>                                           (
<bitbot>                                           _
<bitbot>                                          [
<bitbot> -+--+--+--+--+--+--+--+--+--+--+--+--+--+[_
<bitbot> \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\o
<bitbot> +--+--+--+--+--+--+--+--+--+--+--+--+--+--+

**Comment by bbriggs** [comment]
ummmm

**Comment by jxhn** [comment]
I'd like to formally veto this request

**Comment by PaulGWebster** [comment]
> I'd like to formally veto this request

I would like to formally veto this user

**Comment by bbriggs** [comment]
Feel free to write your own bitbot-compatible plugin and link it in a private instance of bitbot. The API is well documented but I don't feel like this belongs in bitbot's core set of plugins.
