### ISSUE TITLE
bitbot leaves channel upon mentioning it

### ISSUE THREAD

**Issue by rfc2119** [bbriggs/bitbot#139]
## Description
bitbot silently leaves a channel he's in upon starting seeing a phrase that matches the regex "^bitbot.*". Thoughts @m-242 ?

version:  version v1.2.2 (heads/v1.2.2/a2be240)

## Steps to reproduce 
Saying "bitbot" at the beginning of your sentence will make it part

**Comment by m-242** [comment]
The problem comes from the `PartTrigger`, in the `bitbot/channels.go` file, on line 26.

The bot parts a channel when this expression is true:
```go
m.Command == "PRIVMSG" && strings.HasPrefix(m.Content, irc.Nick)
```

We need to have a better regex, to match exactly `bitbot part` and nothing else.
