### ISSUE TITLE
Adapt golangci-lint workflow or refactor to comply with it

### ISSUE THREAD

**Issue by m-242** [bbriggs/bitbot#145]
We are running golangci-lint with the `--enable-all --exclude-use-default=false` flags, which pick up on some needed global variables in the `cmd/root.go` file, among other errors.

**Comment by m-242** [comment]
Some errors are relevant, I will push a fix for at least a part of these during the day.

**Comment by bbriggs** [comment]
Does our lint tool have a skip/ignore flag via in-line comments like most others do?

**Comment by m-242** [comment]
Yes, but I believe we would need to define it with the `-e $ignore_string` flag.

Another solution would be only use the linters we need, but I don't know if that's wise.

Anyways, we could also use the config file it can be any of `.golangci.(yml|toml|json)`.
