### ISSUE TITLE
Missing error checks (and a couple more)

### ISSUE THREAD

**Issue by staticnotdynamic** [bbriggs/bitbot#157]
Keeping this here for future references:
1. no error checks when binding flags with viper
https://github.com/bbriggs/bitbot/blob/8cf41ac578a1e098611763b6e660739bee6a107e/cmd/root.go#L150

2. one more error check here
https://github.com/bbriggs/bitbot/blob/8cf41ac578a1e098611763b6e660739bee6a107e/bitbot/ipinfo.go#L86

3. printf-style function with dynamic format string and no further arguments should use print-style function instead
https://github.com/bbriggs/bitbot/blob/8cf41ac578a1e098611763b6e660739bee6a107e/bitbot/decisions_test.go#L26
https://github.com/bbriggs/bitbot/blob/8cf41ac578a1e098611763b6e660739bee6a107e/bitbot/decisions_test.go#L35

## Explanation for the third point
Using `fmt.Printf` with a dynamic first argument can lead to unexpected output. The first argument is a format string, where certain character combinations have special meaning. If, for example, a user were to enter a string such as

```
Interest rate: 5%
```

and you printed it with

```
fmt.Printf(s)
```

.. it would lead to the following output:

```
Interest rate: 5%!(NOVERB).
```

Similarly, forming the first parameter via string concatenation with user input should be avoided for the same reason. When printing user input, either use a variant of `fmt.Print`, or use the `%s` Printf verb and pass the string as an argument.

**Comment by m-242** [comment]
>     2. one more error check here
>        https://github.com/bbriggs/bitbot/blob/8cf41ac578a1e098611763b6e660739bee6a107e/bitbot/ipinfo.go#L86

This one is a false positive from the linter, I believe it is due to another function of the `http` package named similarly, but applying to a Server struct, instead of a Body where it is the case here.
We should still use `defer` here though.
