### ISSUE TITLE
Event Setting Trigger

### ISSUE THREAD

**Issue by m-242** [bbriggs/bitbot#162]
This trigger would be used to set up events with several members of a channel participating to it.

The event takes place at a given time, has a channel in which all participating people __must__ be, a description, and an author with elevated privileges on the reminder.
For simplicity's sake, a reminder object also has a unique id.

At an event's time, the bot should send a message in the channel containing the event description, and the interested people's nicknames.

The trigger has an activating keyword that might change in the future, but will be considered to be `!reminder` for now.

Following that main keyword should be other keywords precising the action that should be executed:
+ `list` : lists exisiting reminders in the calling channel in the `id | description | author | interested people | time of event` format.
+ `time` : outputs UTC time, to help that don't live in Greenwich get an idea of when is an event taking place.
+ `add $TIME $DESC` : adds a reminder in the message's channel, with the message author as an event author. People should sign for an event themselves, to avoid reminder spam, except for the author that should be added in the interested people's list by default.
The bot should reply with the event's id, description and set time.
+ `remove $ID` : Checks that the event's designed by it's id's author is the one making the call, and then deletes the event.
+ `join $ID` : Adds the message author to the event's interested people's list.
+ `part $ID` : Removes the message author from the event's interested people's list.

Other commands might make the command easier to use, like a command allowing to alter an event, but these will be looked into after creating this basis.

**Comment by m-242** [comment]
On the DB schema :
As of now, we are using PostgresSQL, a SQL DB.

I believe the following schema might be appropriate to the storage of reminders : 

| Property | Type |
| --- | --- |
| ID (unique) |  `unsigned int` |
| Channel |  `string` |
| Author Nick |  `string` |
| Description | `string` |
| Interested Peoples | `string` |
| Time | `golang Time` |

We need the ID to be unique to avoid any event conflicts.
Using nicks to identify people isn't much of a security problem, since any server needing proper authentification will have a Nickserv running.
Interested people should be written with as `nick1@nick2@...` as using an illegal character in a nick as a separator reduces the chances of having a "nick injection".
Using Golang's Time structure will allow us to have an easy comparison, which is great.

**Comment by linkin-park** [comment]
Why cant we use something smaller as DB?

**Comment by m-242** [comment]
See the branch `feature/reminder`.

**Comment by m-242** [comment]
I changed the separating character in the "interested people" field from `@` to ` ` (space), because it allows to highlight said interested people in an easier fashion, and has the same "nick injection protection" properties.
