### ISSUE TITLE
Update or Remove DeepSource configuration file.

### ISSUE THREAD

**Issue by m-242** [bbriggs/bitbot#169]
[This bug](https://github.com/bbriggs/bitbot/blob/ed6049b7cad3c8eca0ebe5a35e462ff42a424851/.deepsource.toml#L8) in the `.deepsource.toml` makes me believe that this file has been merged from one of @staticnotdynamic's pull requests, and not rewritten to fit this repository.

While it would be a very simple fix, I have not heard of deepsource and have no idea of the costs it brings, so I guess we should discuss it here.

**Comment by staticnotdynamic** [comment]
Deepsource provides static analysis for Go source code. Indeed, this one (the deepsource instance) is used only by my account to perform analysis. The repository owner should use it instead.

I used deepsource with a pro license. It cannot be applied on your repository. If you want to continue using it, the repo owner have to setup deepsource himself as I'm seeing it. You can close this issue after removing the configuration file
