### ISSUE TITLE
Limit Bitbot's URL title responses to once every N minutes

### ISSUE THREAD

**Issue by bbriggs** [bbriggs/bitbot#21]
Prevent loops and link spam

**Comment by bbriggs** [comment]
Using the existing boltdb as a cache is probably a good start.

**Comment by sylmoss** [comment]
When you say cache, do you mean a queue of URL to get the titles one by one every N minutes?

**Comment by sylmoss** [comment]
I'd like to try this one as well

**Comment by bbriggs** [comment]
Sure thing. I can line up issues for days if you're interested :)

**Comment by sylmoss** [comment]
Created the PR but I wasn't able to test it. Let me know if the code looks right and also how can I test it.

**Comment by sylmoss** [comment]
I've opened a PR but I wasn't able to test it. Could you please tell me how can I do it and also if the code is right? :)

**Comment by bbriggs** [comment]
I think you're on the right track, but I left some comments in the PR.

**Comment by sylmoss** [comment]
I've made the changes related to your comments in the PR.

**Comment by bbriggs** [comment]
I'm out of town this week and will try to get to all the PRs and issues as soon as I can. Sorry for any delay.

**Comment by m-242** [comment]
So in fact, what we would need is not a cache for every url, but a global cache for every urls, and we only call GetHtmlTitle when the last registered call was more than 2 mins ago.
Is it really useful, as issue #61's answer would take care of most of this problem ?

**Comment by bbriggs** [comment]
Are you sure that's the correct issue?

**Comment by m-242** [comment]
#61 ? Forget about that, I was forgetting what mjolnir's purpose is.
The first paragraph, it's the way I interpret the issue, am I wrong ?

**Comment by m-242** [comment]
Taken care of by PR #66
