### ISSUE TITLE
Add controls to re-initialize (clear) and bootstrap markov model

### ISSUE THREAD

**Issue by bbriggs** [bbriggs/bitbot#81]
Commands should be `!markov reset` and `!markov init` 

`reset` should reinitialize the model and set it back to a fresh state

`init` should pull in a sample/base corpus and pass it to the markov model for training. Desired base texts are K&R C manual, King James Bible, and maybe a copy of a good sci-fi novel for good measure.

**Comment by bbriggs** [comment]
Bible: https://gist.github.com/bbriggs/60e907f3571a1ca7c41cd99f78052d78

**Comment by bbriggs** [comment]
CIA world factbook https://gist.github.com/bbriggs/f63340a3ed1a1439b6f3f8d619eacac1

**Comment by parsec** [comment]
snwcrsh: https://gist.github.com/parsec/2f4d4edf55336c0a2994cfcf951a8ea7
